_editables: {}
_inputs: {}
_select_data: {}
_structures: {}
base_url: www.facebook.com
collections_config:
  pages:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    filter: strict
    icon: notes
    output: true
    parse_branch_index: true
    path: content
    schema_key: _schema
  blog:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    icon: notes
    output: true
    path: content/blog
    schema_key: _schema
  data:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    icon: notes
    output: false
    path: data
    schema_key: _schema
collections_config_override: false
data_config: {}
paths:
  uploads: static/uploads
  static: static
  collections: content
  data: data
  layouts: layouts
  includes: layouts
timezone: Etc/GMT-6
